In [1]:
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt

In [2]:
latest_ratings = pd.read_csv("latest_merlin_ratings.csv")
latest_ratings.shape

(850, 32)

In [3]:
latest_ratings.head()

,id,name,security_type,city,state_name,annual_revenue,created_at,entity_id,price_rating,market_rating,...,advanced_ratings_relevant_industry_experience_rating,advanced_ratings_exits_rating,advanced_ratings_monthly_burn_rate_rating,advanced_ratings_product_risk_rating,advanced_ratings_funding_risk_rating,advanced_ratings_team_risk_rating,advanced_ratings_market_risk_rating,advanced_ratings_legal_risk_rating,advanced_ratings_investment_terms_risk_rating,advanced_ratings_time_risk_ratings
0,1,2XL Swagger Brands,Equity - Common,Austin,Texas,325734.0,2021-01-05 01:01:40,55867,1.8,3.1,...,4.58,1.00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,Monetran,Equity - Tokens,Hockessin,Delaware,0.0,2021-01-05 01:00:47,55639,4.8,4.8,...,1.42,1.00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,Piestro,Equity - Common,Santa Monica,California,0.0,2021-01-05 01:02:18,56026,3.1,3.7,...,3.74,4.58,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,Hundy,Convertible Note,Miami,Florida,26815.0,2021-01-05 01:01:34,55842,3.7,3.7,...,2.68,1.00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,Snailz,SAFE,New York,New York,69932.0,2021-01-05 01:00:37,55599,2.7,3.5,...,1.84,1.00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
new_df = latest_ratings[['id', 'name', 'security_type', 'state_name', 'annual_revenue', 'overall_rating']]
new_df.head()

,id,name,security_type,state_name,annual_revenue,overall_rating
0,1,2XL Swagger Brands,Equity - Common,Texas,325734.0,3.7
1,2,Monetran,Equity - Tokens,Delaware,0.0,2.9
2,3,Piestro,Equity - Common,California,0.0,3.7
3,4,Hundy,Convertible Note,Florida,26815.0,3.3
4,5,Snailz,SAFE,New York,69932.0,2.3