In [1]:
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt

In [2]:
ratings_data = pd.read_csv("new_ratings_data_cleaned.csv", encoding='latin_1')
ratings_data.shape

(326, 126)

In [3]:
ratings_data.head()

,writer,cik,company,date_created,platform,platform_url,sec_filing_url,sec_filing_date,legal_name,dba,...,spacer founder 9,founder_9_relevant_industry_experience,founder_9_previous_startups,founder_9_exits,founder_9_age,founder_9_graduated_from_top_100,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125
0,Olivia,1778006.0,Weeds Never Sleep,7/3/2019 11:08,TruCrowd,https://us.trucrowd.com/equity/offer-summary/W...,https://disclosurequest.com/form/weeds-never-s...,6/25/2019,Weeds Never Sleep LLC,Weeds Never Sleep or HotZot,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Olivia,1720258.0,StorEn Technologies,7/4/2019 8:55,StartEngine,https://www.startengine.com/storen-technologies,https://www.sec.gov/Archives/edgar/data/172025...,7/3/2019,StorEn Technologies,StorEn Technologies,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Olivia,1753677.0,Palouse Ag-Drone Services,7/11/2019 14:41,Razitall,https://www.razitall.com/pitch/the-ag-drone-an...,https://disclosurequest.com/form/palouse-ag-dr...,10/4/2018,Palouse Ag-Drone Services LLC,The Ag-Drone,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Olivia,1765620.0,El Tinieblo International,7/13/2019 10:14,StartEngine,https://www.startengine.com/el-tinieblo-intern...,https://www.sec.gov/Archives/edgar/data/176562...,7/12/2019,"El Tinieblo International, Inc.",El Tinieblo International,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Olivia,1777377.0,Spero CBD,7/16/2019 10:34,StartEngine,https://www.startengine.com/spero-cbd,https://www.sec.gov/Archives/edgar/data/177737...,7/15/2019,Noble Naturals,Spero CBD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
ratings_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 326 entries, 0 to 325
Columns: 126 entries, writer to Unnamed: 125
dtypes: float64(63), object(63)
memory usage: 321.0+ KB

In [5]:
ratings_data.columns

Index(['writer', 'cik', 'company', 'date_created', 'platform', 'platform_url',
       'sec_filing_url', 'sec_filing_date', 'legal_name', 'dba',
       ...
       'spacer founder 9', 'founder_9_relevant_industry_experience',
       'founder_9_previous_startups', 'founder_9_exits', 'founder_9_age',
       'founder_9_graduated_from_top_100', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125'],
      dtype='object', length=126)

In [6]:
ratings_data.describe()

,cik,rev_share_return_multiple,valuations_combined,market_size_total,market_size_addressable,total_revenue,monthly_burn,monthly_burn_rate,relevant_partners,founders,...,founder_8_age,founder_8_graduated_from_top_100,spacer founder 9,founder_9_relevant_industry_experience,founder_9_exits,founder_9_age,founder_9_graduated_from_top_100,Unnamed: 122,Unnamed: 123,Unnamed: 124
count,3.140000e+02,30.000000,2.750000e+02,3.140000e+02,3.140000e+02,3.140000e+02,312.000000,314.000000,314.000000,314.000000,...,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0
mean,1.766095e+06,1.585000,9.417198e+06,4.186561e+11,2.553118e+11,3.723411e+05,22163.352564,0.482779,4.968153,1.633758,...,0.0,0.0,0.0,49.0,NaN,NaN,13.0,0.0,0.0,39.0
std,5.553635e+04,0.398737,1.310159e+07,2.229669e+12,2.113630e+12,1.315171e+06,53835.701404,0.480289,35.585728,0.891712,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.398488e+06,1.000000,0.000000e+00,1.000000e+07,1.000000e+06,0.000000e+00,0.000000,0.000000,0.000000,1.000000,...,0.0,0.0,0.0,49.0,NaN,NaN,13.0,0.0,0.0,39.0
25%,1.753142e+06,1.300000,3.200000e+06,9.914000e+09,1.000000e+09,0.000000e+00,262.750000,0.024450,0.000000,1.000000,...,0.0,0.0,0.0,49.0,NaN,NaN,13.0,0.0,0.0,39.0
50%,1.787346e+06,1.500000,5.600000e+06,4.673000e+10,8.340000e+09,2.394000e+03,3735.500000,0.086700,0.000000,1.000000,...,0.0,0.0,0.0,49.0,NaN,NaN,13.0,0.0,0.0,39.0
75%,1.797639e+06,1.750000,1.000000e+07,1.855000e+11,3.168000e+10,1.835465e+05,19204.250000,1.000000,1.000000,2.000000,...,0.0,0.0,0.0,49.0,NaN,NaN,13.0,0.0,0.0,39.0
max,1.808346e+06,3.000000,1.200000e+08,2.980000e+13,2.980000e+13,1.844223e+07,565876.000000,1.000000,500.000000,9.000000,...,0.0,0.0,0.0,49.0,NaN,NaN,13.0,0.0,0.0,39.0

In [7]:
#pd.set_option("display.precision", 2)
#ratings_data.tail()

In [8]:
ratings_data.describe(include=np.object)

,writer,company,date_created,platform,platform_url,sec_filing_url,sec_filing_date,legal_name,dba,industry,...,has_famous_founders,founder_1_graduated_from_top_100,founder_2_graduated_from_top_100,founder_3_graduated_from_top_100,founder_4_graduated_from_top_100,founder_5_graduated_from_top_100,spacer founder 7,founder_8_relevant_industry_experience,founder_9_previous_startups,Unnamed: 125
count,314,314,274,314,314,314,314,314,307,314,...,314,314,126,32,10,2,1,1,1,1
unique,4,314,274,20,314,314,144,314,307,72,...,2,2,2,2,3,1,1,1,1,1
top,Dan,Airemos,2/5/2020 16:40,StartEngine,https://app.honeycombcredit.com/en/projects/11...,https://www.sec.gov/Archives/edgar/data/180077...,2/28/2020,"Snake Oil Song, LLC",Stone's Throw Hash,Food & Beverages,...,No,No,No,No,No,No,No,No,No,No
freq,151,1,1,78,1,1,10,1,1,38,...,303,248,94,22,5,2,1,1,1,1

In [9]:
pd.set_option("display.max.columns", None)

In [10]:
ratings_data.head()

,writer,cik,company,date_created,platform,platform_url,sec_filing_url,sec_filing_date,legal_name,dba,industry,tech_sector,stage,series,crowdfunding_type_1,crowdfunding_type_2,security_type,rev_share_return_multiple,debt_interest_rate,pre_money_valuation,valuation_cap,discount_rate,valuation_cap_after_discount,valuations_combined,valuations_brackets,revenue_model,distrubution_model,business_type,has_scalable_business_model,margin_level,capital_intensity_level,accelerator_program,market_size_total,market_size_total_buckets,market_size_addressable,market_size_addressable_buckets,market_growth_rate,market_growth_rate_buckets,direct_competitors,differentiation_level_quality,differentiation_level_price,how_is_it_10x_better,barriers_to_entry,threat_of_substitute_products,has_social_impact,has_patents,has_users,has_paying_customers,total_revenue,total_revenue_brackets,monthly_burn,prior_rounds_total_amount_raised,prior_rounds_total_amount_raised_buckets,monthly_burn_rate,monthly_burn_rate_of_capital_buckets,development_phase,bio_development_phase,has_partnerships,relevant_partners,founders,has_shared_experience,has_female_founders,has_minority_founders,has_famous_founders,unique_universities,employees,relevent_advisors,notable_investors,spacer founder 1,founder_1_relevant_industry_experience,founder_1_previous_startups,founder_1_exits,founder_1_age,founder_1_graduated_from_top_100,spacer founder 2,founder_2_relevant_industry_experience,founder_2_previous_startups,founder_2_exits,founder_2_age,founder_2_graduated_from_top_100,spacer founder 3,founder_3_relevant_industry_experience,founder_3_previous_startups,founder_3_exits,founder_3_age,founder_3_graduated_from_top_100,spacer founder 4,founder_4_relevant_industry_experience,founder_4_previous_startups,founder_4_exits,founder_4_age,founder_4_graduated_from_top_100,spacer founder 5,founder_5_relevant_industry_experience,founder_5_previous_startups,founder_5_exits,founder_5_age,founder_5_graduated_from_top_100,spacer founder 6,founder_6_relevant_industry_experience,founder_6_previous_startups,founder_6_exits,founder_6_age,founder_6_graduated_from_top_100,spacer founder 7,founder_7_relevant_industry_experience,founder_7_previous_startups,founder_7_exits,founder_7_age,founder_7_graduated_from_top_100,spacer founder 8,founder_8_relevant_industry_experience,founder_8_previous_startups,founder_8_exits,founder_8_age,founder_8_graduated_from_top_100,spacer founder 9,founder_9_relevant_industry_experience,founder_9_previous_startups,founder_9_exits,founder_9_age,founder_9_graduated_from_top_100,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125
0,Olivia,1778006.0,Weeds Never Sleep,7/3/2019 11:08,TruCrowd,https://us.trucrowd.com/equity/offer-summary/W...,https://disclosurequest.com/form/weeds-never-s...,6/25/2019,Weeds Never Sleep LLC,Weeds Never Sleep or HotZot,Consumer Goods,AgriTech,Early,Pre-Seed,RegCF,NaN,SAFE,NaN,NaN,NaN,"$2,500,000",0%,"$2,500,000",2500000.0,#NAME?,Transactional,B2C,Life Style,No,High,High,No,1.600000e+10,#NAME?,1.000000e+09,#NAME?,2.70%,#NAME?,6,High,Low,Similar to others,Low,High,No,Yes,No,No,0.0,#NAME?,10483.0,$0,#NAME?,1.0000,#NAME?,Pre-Revenue,NaN,No,0.0,2.0,No,Yes,No,No,3.0,2.0,3.0,0.0,NaN,9.0,0.0,0.0,50.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Olivia,1720258.0,StorEn Technologies,7/4/2019 8:55,StartEngine,https://www.startengine.com/storen-technologies,https://www.sec.gov/Archives/edgar/data/172025...,7/3/2019,StorEn Technologies,StorEn Technologies,Consumer Goods,CleanTech,Early,Pre-Seed,RegCF,NaN,Equity - Common,NaN,NaN,"$28,100,000",NaN,NaN,NaN,28100000.0,#NAME?,Transactional,B2C,Life Style,No,High,High,Yes,8.000000e+09,#NAME?,4.000000e+08,#NAME?,38.00%,#NAME?,10,High,Low,Similar to others,High,High,Yes,No,No,No,0.0,#NAME?,40745.0,"$659,800",#NAME?,0.0618,#NAME?,Pre-Revenue,NaN,Yes,2.0,2.0,Yes,No,No,No,5.0,4.0,7.0,0.0,NaN,1.0,0.0,0.0,53.0,No,NaN,15.0,2.0,2.0,50.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Olivia,1753677.0,Palouse Ag-Drone Services,7/11/2019 14:41,Razitall,https://www.razitall.com/pitch/the-ag-drone-an...,https://disclosurequest.com/form/palouse-ag-dr...,10/4/2018,Palouse Ag-Drone Services LLC,The Ag-Drone,Farming,AgriTech,Early,Pre-Seed,RegCF,NaN,CAFES,NaN,NaN,NaN,"$400,000",0%,"$400,000",400000.0,#NAME?,Transactional,B2C,Life Style,No,High,High,No,5.800000e+09,#NAME?,1.200000e+09,#NAME?,31.40%,#NAME?,7,Low,High,Similar to others,Low,High,No,No,No,No,0.0,#NAME?,0.0,$0,#NAME?,1.0000,#NAME?,Pre-Product,NaN,No,0.0,1.0,No,No,No,No,0.0,1.0,0.0,0.0,NaN,0.0,0.0,0.0,45.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Olivia,1765620.0,El Tinieblo International,7/13/2019 10:14,StartEngine,https://www.startengine.com/el-tinieblo-intern...,https://www.sec.gov/Archives/edgar/data/176562...,7/12/2019,"El Tinieblo International, Inc.",El Tinieblo International,Wine & Spirits,Non-Tech,Early,Pre-Seed,RegCF,NaN,Equity - Common,NaN,NaN,"$7,500,000",NaN,NaN,NaN,7500000.0,#NAME?,Transactional,B2B2C,Life Style,No,Low,High,No,1.500000e+09,#NAME?,2.420000e+08,#NAME?,13.00%,#NAME?,240,High,Low,Similar to others,Low,High,No,No,No,No,0.0,#NAME?,564.0,$0,#NAME?,1.0000,#NAME?,Pre-Revenue,NaN,Yes,1.0,1.0,No,No,No,No,1.0,9.0,1.0,0.0,NaN,0.0,2.0,0.0,45.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Olivia,1777377.0,Spero CBD,7/16/2019 10:34,StartEngine,https://www.startengine.com/spero-cbd,https://www.sec.gov/Archives/edgar/data/177737...,7/15/2019,Noble Naturals,Spero CBD,Cannabis and CBD,Non-Tech,Early,Pre-Seed,RegCF,NaN,Convertible Note,NaN,NaN,NaN,"$6,000,000",20%,"$4,800,000",4800000.0,#NAME?,Transactional,B2C,Life Style,Yes,High,High,No,3.080000e+11,#NAME?,2.700000e+08,#NAME?,44.00%,#NAME?,25,High,Low,Similar to others,High,High,No,No,No,Yes,140.0,#NAME?,2380.0,$0,#NAME?,1.0000,#NAME?,Pre-Profit,NaN,No,0.0,4.0,No,Yes,No,No,3.0,8.0,1.0,0.0,NaN,0.0,1.0,0.0,42.0,No,NaN,15.0,0.0,0.0,NaN,No,NaN,0.0,0.0,0.0,42.0,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
valuation = ratings_data["valuations_combined"]
revenue = ratings_data["total_revenue"]
addressable_market = ratings_data["market_size_addressable"]
total_market = ratings_data["market_size_total"]
market_growth = ratings_data["market_growth_rate"]
burn_rate = ratings_data["monthly_burn_rate"]

In [12]:
ratings_data.dtypes

writer                                     object
cik                                       float64
company                                    object
date_created                               object
platform                                   object
platform_url                               object
sec_filing_url                             object
sec_filing_date                            object
legal_name                                 object
dba                                        object
industry                                   object
tech_sector                                object
stage                                      object
series                                     object
crowdfunding_type_1                        object
crowdfunding_type_2                        object
security_type                              object
rev_share_return_multiple                 float64
debt_interest_rate                         object
pre_money_valuation                        object
valuation_cap                              object
discount_rate                              object
valuation_cap_after_discount               object
valuations_combined                       float64
valuations_brackets                        object
revenue_model                              object
distrubution_model                         object
business_type                              object
has_scalable_business_model                object
margin_level                               object
                                           ...
founder_5_age                             float64
founder_5_graduated_from_top_100           object
spacer founder 6                          float64
founder_6_relevant_industry_experience    float64
founder_6_previous_startups               float64
founder_6_exits                           float64
founder_6_age                             float64
founder_6_graduated_from_top_100          float64
spacer founder 7                           object
founder_7_relevant_industry_experience    float64
founder_7_previous_startups               float64
founder_7_exits                           float64
founder_7_age                             float64
founder_7_graduated_from_top_100          float64
spacer founder 8                          float64
founder_8_relevant_industry_experience     object
founder_8_previous_startups               float64
founder_8_exits                           float64
founder_8_age                             float64
founder_8_graduated_from_top_100          float64
spacer founder 9                          float64
founder_9_relevant_industry_experience    float64
founder_9_previous_startups                object
founder_9_exits                           float64
founder_9_age                             float64
founder_9_graduated_from_top_100          float64
Unnamed: 122                              float64
Unnamed: 123                              float64
Unnamed: 124                              float64
Unnamed: 125                               object
Length: 126, dtype: object

In [13]:
#int(valuation.replace(',', ''))

In [14]:
ratings_data['total_revenue'].dtypes

dtype('float64')

In [15]:
rev_valuation_corr = revenue.corr(valuation)
rev_valuation_corr

0.30149652915059355

In [16]:
addressable_mkt_valuation_corr = addressable_market.corr(valuation)
addressable_mkt_valuation_corr

0.03658308245732348

In [17]:
total_mkt_valuation_corr = total_market.corr(valuation)
total_mkt_valuation_corr

0.03187805538237101

In [18]:
burn_rate_valuation_corr = burn_rate.corr(valuation)
burn_rate_valuation_corr

-0.19354287430063563

In [19]:
age = ratings_data['founder_1_age']
age_valuation_corr = age.corr(valuation)
age_valuation_corr

0.12914343916991264

In [20]:
rev_burn_corr = revenue.corr(burn_rate)
rev_burn_corr

-0.11780389549123092

In [21]:
ratings_data['revenue_multiple'] = ratings_data['valuations_combined'] / ratings_data['total_revenue']

In [22]:
ratings_data['revenue_multiple']

0               inf
1               inf
2               inf
3               inf
4      3.428571e+04
5               inf
6               inf
7      3.663717e+00
8               inf
9      1.391018e+01
10     6.558859e+00
11              inf
12     2.806470e+00
13              inf
14     6.536268e+00
15     2.907893e+01
16     1.114305e+01
17     9.519277e+01
18     1.279818e+02
19              inf
20     2.709831e+00
21              inf
22              inf
23     7.295942e+01
24              inf
25     8.585174e+00
26     2.061098e+01
27              inf
28     3.777798e+01
29     1.686547e+02
           ...
296             NaN
297             NaN
298             NaN
299             NaN
300             NaN
301             NaN
302             NaN
303             NaN
304             NaN
305             NaN
306             NaN
307             NaN
308             NaN
309             NaN
310             NaN
311             NaN
312             NaN
313             NaN
314             NaN
315             NaN
316             NaN
317             NaN
318             NaN
319             NaN
320             NaN
321             NaN
322             NaN
323    0.000000e+00
324    0.000000e+00
325    0.000000e+00
Name: revenue_multiple, Length: 326, dtype: float64

In [24]:
ratings_data['revenue_multiple'].replace(np.inf, 0, inplace=True)
ratings_data['revenue_multiple']

0          0.000000
1          0.000000
2          0.000000
3          0.000000
4      34285.714286
5          0.000000
6          0.000000
7          3.663717
8          0.000000
9         13.910179
10         6.558859
11         0.000000
12         2.806470
13         0.000000
14         6.536268
15        29.078935
16        11.143045
17        95.192765
18       127.981798
19         0.000000
20         2.709831
21         0.000000
22         0.000000
23        72.959416
24         0.000000
25         8.585174
26        20.610985
27         0.000000
28        37.777983
29       168.654667
           ...
296             NaN
297             NaN
298             NaN
299             NaN
300             NaN
301             NaN
302             NaN
303             NaN
304             NaN
305             NaN
306             NaN
307             NaN
308             NaN
309             NaN
310             NaN
311             NaN
312             NaN
313             NaN
314             NaN
315             NaN
316             NaN
317             NaN
318             NaN
319             NaN
320             NaN
321             NaN
322             NaN
323        0.000000
324        0.000000
325        0.000000
Name: revenue_multiple, Length: 326, dtype: float64

In [26]:
ratings_data.head()

,writer,cik,company,date_created,platform,platform_url,sec_filing_url,sec_filing_date,legal_name,dba,industry,tech_sector,stage,series,crowdfunding_type_1,crowdfunding_type_2,security_type,rev_share_return_multiple,debt_interest_rate,pre_money_valuation,valuation_cap,discount_rate,valuation_cap_after_discount,valuations_combined,valuations_brackets,revenue_model,distrubution_model,business_type,has_scalable_business_model,margin_level,capital_intensity_level,accelerator_program,market_size_total,market_size_total_buckets,market_size_addressable,market_size_addressable_buckets,market_growth_rate,market_growth_rate_buckets,direct_competitors,differentiation_level_quality,differentiation_level_price,how_is_it_10x_better,barriers_to_entry,threat_of_substitute_products,has_social_impact,has_patents,has_users,has_paying_customers,total_revenue,total_revenue_brackets,monthly_burn,prior_rounds_total_amount_raised,prior_rounds_total_amount_raised_buckets,monthly_burn_rate,monthly_burn_rate_of_capital_buckets,development_phase,bio_development_phase,has_partnerships,relevant_partners,founders,has_shared_experience,has_female_founders,has_minority_founders,has_famous_founders,unique_universities,employees,relevent_advisors,notable_investors,spacer founder 1,founder_1_relevant_industry_experience,founder_1_previous_startups,founder_1_exits,founder_1_age,founder_1_graduated_from_top_100,spacer founder 2,founder_2_relevant_industry_experience,founder_2_previous_startups,founder_2_exits,founder_2_age,founder_2_graduated_from_top_100,spacer founder 3,founder_3_relevant_industry_experience,founder_3_previous_startups,founder_3_exits,founder_3_age,founder_3_graduated_from_top_100,spacer founder 4,founder_4_relevant_industry_experience,founder_4_previous_startups,founder_4_exits,founder_4_age,founder_4_graduated_from_top_100,spacer founder 5,founder_5_relevant_industry_experience,founder_5_previous_startups,founder_5_exits,founder_5_age,founder_5_graduated_from_top_100,spacer founder 6,founder_6_relevant_industry_experience,founder_6_previous_startups,founder_6_exits,founder_6_age,founder_6_graduated_from_top_100,spacer founder 7,founder_7_relevant_industry_experience,founder_7_previous_startups,founder_7_exits,founder_7_age,founder_7_graduated_from_top_100,spacer founder 8,founder_8_relevant_industry_experience,founder_8_previous_startups,founder_8_exits,founder_8_age,founder_8_graduated_from_top_100,spacer founder 9,founder_9_relevant_industry_experience,founder_9_previous_startups,founder_9_exits,founder_9_age,founder_9_graduated_from_top_100,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,revenue_multiple
0,Olivia,1778006.0,Weeds Never Sleep,7/3/2019 11:08,TruCrowd,https://us.trucrowd.com/equity/offer-summary/W...,https://disclosurequest.com/form/weeds-never-s...,6/25/2019,Weeds Never Sleep LLC,Weeds Never Sleep or HotZot,Consumer Goods,AgriTech,Early,Pre-Seed,RegCF,NaN,SAFE,NaN,NaN,NaN,"$2,500,000",0%,"$2,500,000",2500000.0,#NAME?,Transactional,B2C,Life Style,No,High,High,No,1.600000e+10,#NAME?,1.000000e+09,#NAME?,2.70%,#NAME?,6,High,Low,Similar to others,Low,High,No,Yes,No,No,0.0,#NAME?,10483.0,$0,#NAME?,1.0000,#NAME?,Pre-Revenue,NaN,No,0.0,2.0,No,Yes,No,No,3.0,2.0,3.0,0.0,NaN,9.0,0.0,0.0,50.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
1,Olivia,1720258.0,StorEn Technologies,7/4/2019 8:55,StartEngine,https://www.startengine.com/storen-technologies,https://www.sec.gov/Archives/edgar/data/172025...,7/3/2019,StorEn Technologies,StorEn Technologies,Consumer Goods,CleanTech,Early,Pre-Seed,RegCF,NaN,Equity - Common,NaN,NaN,"$28,100,000",NaN,NaN,NaN,28100000.0,#NAME?,Transactional,B2C,Life Style,No,High,High,Yes,8.000000e+09,#NAME?,4.000000e+08,#NAME?,38.00%,#NAME?,10,High,Low,Similar to others,High,High,Yes,No,No,No,0.0,#NAME?,40745.0,"$659,800",#NAME?,0.0618,#NAME?,Pre-Revenue,NaN,Yes,2.0,2.0,Yes,No,No,No,5.0,4.0,7.0,0.0,NaN,1.0,0.0,0.0,53.0,No,NaN,15.0,2.0,2.0,50.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
2,Olivia,1753677.0,Palouse Ag-Drone Services,7/11/2019 14:41,Razitall,https://www.razitall.com/pitch/the-ag-drone-an...,https://disclosurequest.com/form/palouse-ag-dr...,10/4/2018,Palouse Ag-Drone Services LLC,The Ag-Drone,Farming,AgriTech,Early,Pre-Seed,RegCF,NaN,CAFES,NaN,NaN,NaN,"$400,000",0%,"$400,000",400000.0,#NAME?,Transactional,B2C,Life Style,No,High,High,No,5.800000e+09,#NAME?,1.200000e+09,#NAME?,31.40%,#NAME?,7,Low,High,Similar to others,Low,High,No,No,No,No,0.0,#NAME?,0.0,$0,#NAME?,1.0000,#NAME?,Pre-Product,NaN,No,0.0,1.0,No,No,No,No,0.0,1.0,0.0,0.0,NaN,0.0,0.0,0.0,45.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
3,Olivia,1765620.0,El Tinieblo International,7/13/2019 10:14,StartEngine,https://www.startengine.com/el-tinieblo-intern...,https://www.sec.gov/Archives/edgar/data/176562...,7/12/2019,"El Tinieblo International, Inc.",El Tinieblo International,Wine & Spirits,Non-Tech,Early,Pre-Seed,RegCF,NaN,Equity - Common,NaN,NaN,"$7,500,000",NaN,NaN,NaN,7500000.0,#NAME?,Transactional,B2B2C,Life Style,No,Low,High,No,1.500000e+09,#NAME?,2.420000e+08,#NAME?,13.00%,#NAME?,240,High,Low,Similar to others,Low,High,No,No,No,No,0.0,#NAME?,564.0,$0,#NAME?,1.0000,#NAME?,Pre-Revenue,NaN,Yes,1.0,1.0,No,No,No,No,1.0,9.0,1.0,0.0,NaN,0.0,2.0,0.0,45.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
4,Olivia,1777377.0,Spero CBD,7/16/2019 10:34,StartEngine,https://www.startengine.com/spero-cbd,https://www.sec.gov/Archives/edgar/data/177737...,7/15/2019,Noble Naturals,Spero CBD,Cannabis and CBD,Non-Tech,Early,Pre-Seed,RegCF,NaN,Convertible Note,NaN,NaN,NaN,"$6,000,000",20%,"$4,800,000",4800000.0,#NAME?,Transactional,B2C,Life Style,Yes,High,High,No,3.080000e+11,#NAME?,2.700000e+08,#NAME?,44.00%,#NAME?,25,High,Low,Similar to others,High,High,No,No,No,Yes,140.0,#NAME?,2380.0,$0,#NAME?,1.0000,#NAME?,Pre-Profit,NaN,No,0.0,4.0,No,Yes,No,No,3.0,8.0,1.0,0.0,NaN,0.0,1.0,0.0,42.0,No,NaN,15.0,0.0,0.0,NaN,No,NaN,0.0,0.0,0.0,42.0,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34285.714286

In [27]:
revenue_multiple = ratings_data['revenue_multiple']

In [29]:
rev_multiple_rev_corr = revenue_multiple.corr(revenue)
rev_multiple_rev_corr

-0.0261587493874618

In [30]:
rev_multiple_burn_corr = revenue_multiple.corr(burn_rate)
rev_multiple_burn_corr

0.07695779110269875

In [31]:
rev_multiple_add_mkt_corr = revenue_multiple.corr(addressable_market)
rev_multiple_add_mkt_corr

-0.008749647080233807

In [33]:
rev_multiple_age_corr = revenue_multiple.corr(age)
rev_multiple_age_corr

-0.013492164848768388

In [ ]:
ratings_data['revenue']